from __future__ import annotations

import argparse
import os
from pathlib import Path

from huggingface_hub import HfApi, create_repo


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-repo-id", default="ShiroOnigami23/securehealthiot-disease-model")
    parser.add_argument("--dataset-repo-id", default="ShiroOnigami23/securehealthiot-disease-dataset")
    parser.add_argument("--outputs-dir", default="kaggle_outputs")
    args = parser.parse_args()

    token = os.environ.get("HF_TOKEN", "")
    if not token:
        raise RuntimeError("HF_TOKEN env var is required.")

    out_dir = Path(args.outputs_dir)
    model_bundle = out_dir / "model_bundle.joblib"
    metrics = out_dir / "metrics.json"
    cleaned = out_dir / "cleaned_dataset.csv"
    for p in [model_bundle, metrics, cleaned]:
        if not p.exists():
            raise FileNotFoundError(f"Missing expected output: {p}")

    api = HfApi(token=token)

    create_repo(args.model_repo_id, token=token, repo_type="model", exist_ok=True)
    api.upload_file(
        path_or_fileobj=str(model_bundle),
        path_in_repo="latest_model.joblib",
        repo_id=args.model_repo_id,
        repo_type="model",
    )
    api.upload_file(
        path_or_fileobj=str(metrics),
        path_in_repo="kaggle_metrics.json",
        repo_id=args.model_repo_id,
        repo_type="model",
    )

    create_repo(args.dataset_repo_id, token=token, repo_type="dataset", exist_ok=True)
    api.upload_file(
        path_or_fileobj=str(cleaned),
        path_in_repo="cleaned_dataset.csv",
        repo_id=args.dataset_repo_id,
        repo_type="dataset",
    )
    api.upload_file(
        path_or_fileobj=str(metrics),
        path_in_repo="training_metrics.json",
        repo_id=args.dataset_repo_id,
        repo_type="dataset",
    )

    readme = Path("kaggle_outputs/HF_DATASET_README.md")
    readme.write_text(
        "# SecureHealthIoT Cleaned Dataset\n\n"
        "Cleaned symptom-disease dataset generated by Kaggle kernel run:\n"
        "`aryansingh21fd/securehealthiot-disease-trainer-v1`.\n",
        encoding="utf-8",
    )
    api.upload_file(
        path_or_fileobj=str(readme),
        path_in_repo="README.md",
        repo_id=args.dataset_repo_id,
        repo_type="dataset",
    )

    print(f"Model repo updated: https://huggingface.co/{args.model_repo_id}")
    print(f"Dataset repo updated: https://huggingface.co/datasets/{args.dataset_repo_id}")


if __name__ == "__main__":
    main()
